#init
data_dir: /data
gpgkey: https://mirrors.aliyun.com
#docker
#docker_version: docker-ce-19.03.1 #单独安装docker时使用此版本
# 18.09.2 19.03.5
docker_version: 19.03.5
docker_data_dir: /var/lib
docker_bip: 169.254.123.1/24
docker_url: "https://ops-files.obs.cn-east-2.myhuaweicloud.com/pkg/docker/docker-{{ docker_version }}.tar.gz"
#etcd v3.3.8 v3.4.3
etcd_version: v3.3.8
etcd_dir: "/opt/etcd-{{ etcd_version  }}"
etcd_data_dir: /var/lib/etcd
etcd_url: "https://ops-files.obs.cn-east-2.myhuaweicloud.com/pkg/etcd/etcd-{{ etcd_version  }}.tar.gz"
etcd_token: c533f5tb-2d99-4060-9d64-bf4143d2a799
#证书
ssl_dir: /opt/cert
#k8s
#kubernetes_version: 1.12.6-aliyun.1
#kubernetes_version: 1.14.6-aliyun.1
#kubernetes_version: 1.14.8-aliyun.1
kubernetes_version: 1.16.6-aliyun.1
#kubernetes_version: 1.15.4
kubernetes_url: "https://ops-files.obs.cn-east-2.myhuaweicloud.com/pkg/kubernetes/kubernetes-{{ kubernetes_version }}.tar.gz"
kube_certs_time: 3650
#1.15.4使用这个地址
#kube_image_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers"
#1.12.6-aliyun.1,1.14.6-aliyun.1和1.14.8-aliyun.1使用这个地址
kube_image_repo: "registry.cn-hangzhou.aliyuncs.com/acs"
# K8s image pull policy (imagePullPolicy)
k8s_image_pull_policy: IfNotPresent
kube_dns_domain: "cluster.local"
kube_service_addresses: 10.64.0.0/16
kube_apiserver_ip: "{{ kube_service_addresses|ipaddr('net')|ipaddr(1)|ipaddr('address') }}"
kube_dns_server: "{{ kube_service_addresses|ipaddr('net')|ipaddr(10)|ipaddr('address') }}"
kube_pods_subnet: 10.63.0.0/16
kube_apiserver_node_port_range: 30000-32767
kube_apiserver_port: 6443
kube_proxy_mode: ipvs
#kube_proxy_mode: iptables
kubeadm_token: fpn5l0.mfegiopmlnlsk6bb  #新加节点时记得更新此token
#升级时是否驱逐节点上的容器组
drain_nodes: false
need_check_kubelet_version: false
#负载均衡
keepalived_enable: true
loadbalancer_apiserver_ip: 10.75.1.180
loadbalancer_apiserver_port: 5443
loadbalancer_apiserver_keepalive_timeout: 5m
loadbalancer_apiserver_healthcheck_port: 8081
loadbalancer_apiserver_cpu_requests: 25m
loadbalancer_apiserver_memory_requests: 32M
nginx_image_repo: nginx
nginx_image_tag: latest
nginx_config_dir: /etc/nginx
#k8s addons
flannel_enable: true
flannel_image_repo: "registry.cn-hangzhou.aliyuncs.com/zalmanzhao/flannel"
# v0.8.0 v0.9.0 0.11.0 版本可选
flannel_image_tag: "v0.11.0"
coredns_image_repo: "registry.cn-hangzhou.aliyuncs.com/zalmanzhao/coredns"
# 1.3.1  1.6.2 版本可选
coredns_image_tag: "1.6.2"
metrics_server_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers/metrics-server-amd64"
metrics_server_tag: "v0.3.1"
metrics_server_nanny_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers/addon-resizer"
metrics_server_nanny_tag: "1.8.3"
ingress_enable: true
ingress_run_master_enable: true
ingress_namespace: kube-system
ingress_class: nginx
ingress_image_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller"
ingress_image_tag: 0.31.1
dashboard_enable: true
dashboard_run_master_enable: true
dashboard_image_repo: "registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetes-dashboard-amd64"
dashboard_image_tag: "v1.10.1"
heapster_run_master_enable: true
heapster_enable_grafana: false
