#- name: "签发证书"
#  hosts: localhost
#  connection: local
#  roles:
#    - { role: 'etcd-cert', tags: "etcd-cert" }
#- name: "分发证书安装服务"
#  hosts: etcd
#  roles:
#    - { role: 'etcd', tags: "install_etcd" }
- name: "初始化Master节点"
  hosts: kube-master
  roles:
    - { role: 'kubernetes-init', tags: "kubernetes-init" }
- name: "配置HA负载均衡"
  hosts: keepalived
  roles:
    - { role: 'kubernetes-keepalived', tags: "kubernetes-keepalived" }
- name: "配置部署kubernetes"
  hosts: kube-master
  roles:
    - { role: 'kubernetes-master', tags: "kubernetes-master" }
    - { role: 'kubernetes-addons/flannel', tags: 'flannel' }
    - { role: 'kubernetes-addons/coredns', tags: 'coredns' }
    - { role: 'kubernetes-addons/metrics-server', tags: 'metrics-server' }
    - { role: 'kubernetes-addons/nginx-ingress', tags: 'nginx-ingress' }
    - { role: 'kubernetes-addons/dashboard', tags: 'dashboard' }
    - { role: 'kubernetes-addons/heapster', tags: 'heapster' }
