- name: "初始化Master节点"
  hosts: kube-master
  roles:
    - { role: 'kubernetes-init', tags: "kubernetes-init" }
- name: "配置HA负载均衡"
  hosts: keepalived
  roles:
    - { role: 'kubernetes-keepalived', tags: "kubernetes-keepalived" }
- name: "配置部署kubernetes"
  hosts: kube-master
  roles:
    - { role: 'kubernetes-master', tags: "kubernetes-master" }
- name: "配置部署Addons"
  hosts: kube-master
  roles:
    - { role: 'kubernetes-addons/flannel', tags: 'flannel' }
    - { role: 'kubernetes-addons/coredns', tags: 'coredns' }
    - { role: 'kubernetes-addons/metrics-server', tags: 'metrics-server' }
