- name: "Heapster | create heapster config dir"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  when: inventory_hostname == groups['kube-master'][0]
  tags:
    - addons
  with_items:
    - "/etc/kubernetes/addons"
    - "/etc/kubernetes/addons/heapster"

- name: "Heapster | Create heapster manifest"
  template:
    src: heapster.yml.j2
    dest: "/etc/kubernetes/addons/heapster/heapster.yml"
  register: heapster_manifest
  when: inventory_hostname == groups['kube-master'][0]

- name: "Heapster | Start Resources"
  command: "kubectl apply -f /etc/kubernetes/addons/heapster/heapster.yml -n kube-system"
  when: inventory_hostname == groups['kube-master'][0] and heapster_manifest.changed
