- name: "下载java安装包"
  get_url:
    url: "{{ java_url }}"
    dest: /tmp
  tags: java

- name: "创建安装目录"
  file:
    path: "/data"
    state: directory
    owner: root
    group: root
  tags: java

- name: "解压java安装包"
  command: 'tar xzf /tmp/jdk-{{ java_version }}.tar.gz chdir="/data"'
  tags: java

#- name: "移除openjdk'"
#  yum: name=*-openjdk-* state=absent

#- name: "移除gcj包"
#  yum: name=*gcj* state=absent

- name: "设置JAVA_HOME environment"
  lineinfile: dest=/etc/profile regexp="^JAVA_HOME=" line="JAVA_HOME=/data/{{ java_path }}"

- name: "设置PATH environment"
  lineinfile: dest=/etc/profile regexp="^PATH=\$PATH:\$JAVA_HOME" line="PATH=$PATH:$JAVA_HOME/bin"
