- name: "Flannel | create flannel config dir"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  when: inventory_hostname == groups['kube-master'][0]
  tags:
    - addons
  with_items:
    - "/etc/kubernetes/addons"
    - "/etc/kubernetes/addons/flannel"

- name: "Flannel | Create flannel manifest"
  template:
    src: kube-flannel-vxlan.{{ flannel_image_tag }}.yml.j2
    dest: "/etc/kubernetes/addons/flannel/kube-flannel-vxlan.yml"
  register: flannel_manifest
  when: inventory_hostname == groups['kube-master'][0]

- name: "Flannel | Start Resources"
  command: "kubectl apply -f /etc/kubernetes/addons/flannel/kube-flannel-vxlan.yml -n kube-system"
  when: inventory_hostname == groups['kube-master'][0] and flannel_manifest.changed and flannel_enable | default(true)
