- name: "Metrics-Server | create metrics-server config dir"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  when: inventory_hostname == groups['kube-master'][0]
  tags:
    - addons
  with_items:
    - "/etc/kubernetes/addons"
    - "/etc/kubernetes/addons/metrics-server"

- name: "Metrics-Server | Create metrics-server manifest"
  template:
    src: metrics-server.yml.j2
    dest: "/etc/kubernetes/addons/metrics-server/metrics-server.yml"
  register: metrics_server_manifest
  when: inventory_hostname == groups['kube-master'][0]

- name: "Metrics-Server | Start Resources"
  command: "kubectl apply -f /etc/kubernetes/addons/metrics-server/metrics-server.yml -n kube-system"
  when: inventory_hostname == groups['kube-master'][0] and metrics_server_manifest.changed
